server:
  port: 7000

spring:
  profiles:
    active: local
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://192.168.0.11:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: member-service-public
          uri: http://localhost:9010 # lb://microservice
          predicates:
            - Method=POST
            - Path=/members/token/**, /members

        - id: member-service
          uri: http://localhost:9010 # lb://microservice
          predicates:
            - Path=/members/**
          filters:
            - name: AccessTokenDecoding

        - id: recipe-service
          uri: http://localhost:9020
          predicates:
            - Path=/recipes/**
          filters:
            - name: AccessTokenDecoding

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

security:
  jwt:
    validate-time: 1800
    key: recipt-access
    algorithm: HS256
